[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8"
zerocopy = "0.6.0"
byteorder = "1.4.3"
serde = { version = "1.0", features = ["derive"] }
sled = "0.34.7"